### ISSUE TITLE
path is not a valid name for a constant

### ISSUE THREAD

**Issue by AlexKap23** [Layusmen/QuizMaker#10]
https://github.com/Layusmen/QuizMaker/blob/b4d2ce57b08fb3d26a525e42126bbdb04ed99166/QuizMaker/Constants.cs#L12

Follow the same rules as you do with all the other constants on this file. Constant names should always be in upper case letters and if they have more that 1 part, the parts should be separated with underscores.

**Comment by Layusmen** [comment]
Alright. Consider it done.
