### ISSUE TITLE
Why don't you declare this in your Logic.cs

### ISSUE THREAD

**Issue by AlexKap23** [Layusmen/QuizMaker#8]
https://github.com/Layusmen/QuizMaker/blob/b4d2ce57b08fb3d26a525e42126bbdb04ed99166/QuizMaker/Program.cs#L10

Random object is used only inside your Logics class. It would be much better if you declared this inside Logics class instead of declaring it into Program.cs

Same thing applies for your Serializer object as it's used only inside logics class

**Comment by Layusmen** [comment]
Alright
